spring:
  datasource:
    one:
      username: root
      password: admin
      url: jdbc:mysql://localhost:3306/jasmine_users?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
    two:
      username: root
      password: MilkCoco412
      url: jdbc:mysql://localhost:24444/jasmine_amusement?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 45445
  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    max-connections: 8192