spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/jasmine_users?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 45445
  tomcat:
    uri-encoding: UTF-8
